
[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook/*.html" ]

[functions.create-payment-intent]
enabled = true
verify_jwt = false
# Uses default import map
entrypoint = "./functions/create-payment-intent/index.ts"

[functions.send-test-notification]
enabled = true
verify_jwt = false
import_map = "./functions/send-test-notification/deno.json"
entrypoint = "./functions/send-test-notification/index.ts"
